language: node_js
node_js:
- '8'
sudo: enabled
notifications:
  email:
  - jesse.goodenough@gmail.com
before_install:
- npm i -g npm@5.5.x
- chmod 0600 ~/.gnupg/gpg.conf
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
install:
- sudo sed -i '/apache/d' /etc/apt/sources.list
- npm install
- npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: jessegoodenough
  api_key:
    secure: hxRN+rJgcLB4ZQu389DzjhkBzade+RlEYfugA7KCc5/towvuRP1ysCvWgka3MkwNGVDRVpNaABG1USW2Y//QnE3p/gKhoXuI2ce+FuPik/hQfxsXJbKkvBjkpJKLapKpNJARG8C1X6cH+yCD6M82A/JWjO882nHmB8US4ju/MjXAOOymMH4diNX9V+pP7tb1lMz6kNJfkmhydA8Y8W5EanGX6aJHSuDBYwFPSPekY376O1kHs82gunZPubPD6HjcxmnExzVXPdHV5GxXWE6zbdH2uLchPn00jV6ATqXNw77h20Tkijfp6p0t3nWTYlNUoPEnMYXgsOmvB4GMpBi14AtR1dUI5KBgN8P3ITrn5aj8B0YQyyh3cSx76BQ6fH6qN5sY3aAVO5jjIb8KnIWje+w4xYTYOAFhE6zJdbBhm5uk6t0oMlyeRNhT4FuFW2uaekp5xoSuWKaa8+Ix2YmBZMf25Jo748eQ26YsTA7yn6oGmZ61GhN+CT5DKbnrxUqtsTa9ZKsh/dTCNdg/ntkwtGFsD5Ft0k6vkqf0ImDqOpUMHWE0niZdfwNw+U9HgUjXMiv3JPour5kcNwsYjv9vTw9JTNItbUBj6faxOKqq93mzebb0Y2cj0/T7mwyEhfKUtYTNJ1tAau7cSXl77oDVxm93bE1pM93ZhO/DZWmQ7QU=
  skip_cleanup: true
