language: node_js
sudo: enabled
before_install:
- chmod 0600 ~/.gnupg/gpg.conf
deploy:
  provider: heroku
  app: jessegoodenough
  api_key:
    secure: IVPFDRFkHgRrStD2fq1xOJaNoQCltTQyeXDtKd3YIZzWLgbWk6gPaAgWZcdAfal5aSJIl23+xtAxeYig/7deY1r7eLkO4qtCvufhfR4i29MUnshjvtgpM4LBI+RDMvYgbN7GEzfzmNpUjtXRnaNuhhiCvg5r5eUPEcM1dAWi6tbcLk4jNzJdkg2djLCh1lzDc4PQ55zoJ9q151FaD8FiJ5ErG5JNSuLd5mmXGnn29cL0/TE9Yd3DfEOpIhT4tyrF5iWXvkb0WzT8Dcne3YhdbFWSA30VFkxbTj+Py9apCxy3YZHiIPc/Cxf8PZ1QVMbzhDW1Qeq+0NpvukW10iyZAqMdypFNiLlQv5e5OKsV7qSxW5ESYZ0e0zxRuMNV1QiqsU+CZggPAnt2bnAQnsrhA70XPmidVCwj0dbyKBVt15gBQ+4h+B2S+do8DjUK6GhdsoH3b7+jjIf1OI/CdRPjyVGL2nWXrcpjXsQ3IKBtUBhaaqDSLE67wAD7ZeVDR7xyM1UkHOCNHNAEW7ThFr5EsXjX5eLJ1DYtrVw3bxe3731ZjJFetrtehG/coYj0jBRV5dNZAXMq4OZReapEbrN3cK+KXlLY/DZAyaD6SxyaM0XE7QilyC+2tm8b+oIjX9Un2dNBi5e2mPn5zkFRlyKvt2zyVEahIfgAnEt/0vTFRMM=
  run:
  - npm run build
  - npm run start
